In [1]:
import pandas as pd
import os
from dotenv import load_dotenv
from googleapiclient.discovery import build
from youtube import *
from cleaning import *
import spacy

Device set to use cpu
c:\Users\sangi\Documents\GitHub\nlp-politics\.venv\Lib\site-packages\transformers\pipelines\token_classification.py:186: UserWarning: `grouped_entities` is deprecated and will be removed in version v5.0.0, defaulted to `aggregation_strategy="AggregationStrategy.NONE"` instead.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

c:\Users\sangi\Documents\GitHub\nlp-politics\.venv\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sangi\.cache\huggingface\hub\models--sentence-transformers--all-MiniLM-L6-v2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [2]:
load_dotenv()

yt_api_key = os.getenv("YT_API_KEY")
youtube = build("youtube", "v3", developerKey = yt_api_key)

In [56]:
videos_original = pd.read_csv("../data/videos_original.csv")
videos_original.tail()

,title,video_id,channel,transcript
23,“The Climate Change Agenda Is A Hoax” - Vivek ...,keUPHwFFQj4,Vivek Ramaswamy,young people in this country are so hungry for...
24,It's Time To Acknowledge The Climate Crisis Fo...,Wwoq4Yikfko,Vivek Ramaswamy,Vic ramaswamy is the founder and executive cha...
25,Fox News is Definitely Certain that Climate Ch...,nBnVeh9udkk,Fox News,you don't go see Joseph goal's films to see th...
26,BREAKING | Trump At UN: 'Climate Change Is The...,QTLmVwZHQyw,Donald Trump,air conditioner is like very uncommon to see o...
27,Donald Trump's Best Lines on Climate Change,qpyFjUsm2PU,Donald Trump,and I think I know more about the environment ...

In [4]:
videos_punctuation = pd.read_csv("../data/videos_punctuation.csv")
videos_punctuation.head()

,title,video_id,channel,chunks_punctuation
0,CLIMATE COLLAPSE: EXTREME Temperature Records ...,twNs_39Zqa4,Secular Talk,Ben Shapiro. every time he talks about climate...
1,CLIMATE COLLAPSE: EXTREME Temperature Records ...,twNs_39Zqa4,Secular Talk,"called air conditioning. it's awesome, you kno..."
2,CLIMATE COLLAPSE: EXTREME Temperature Records ...,twNs_39Zqa4,Secular Talk,to get off the horse and the buggy. what's wro...
3,CLIMATE COLLAPSE: EXTREME Temperature Records ...,twNs_39Zqa4,Secular Talk,you act like you don't understand that point. ...
4,CLIMATE COLLAPSE: EXTREME Temperature Records ...,twNs_39Zqa4,Secular Talk,drought. there's this thing called famine. the...

In [4]:
stance_targets = ["The person is in favor of climate change policies", "The person is opposed to the climate change policies", "The person has a neutral stance on climate change policies"]

In [ ]:
compute_similarity(videos_punctuation)

# Data preprocessing workflow

1. __Split text__ --> for each video, split text into chunks of about 250 words, each chunk will end up on one different row (for model limits).
2. __Add punctuation__ --> add punctuation to each chunk with a punctuation restoration model (transformer)
3. __Check similarity to topic__ --> for each chunk (row) compute semantic similarity with some phrases (like "climate", "global warming", etc)
3. __Filter by similarity__ -->only keep the chunks that have semantic similarity > threshold (like 0.3 or 0.4 for cosine similarity)
4. __Tokenize__ -->tokenize filtered chunks for stance detection